### PR TITLE
update spago deps, refactor

### PR DESCRIPTION
**Pull request by srghma**

### CODE REVIEW

**Comment by martyall** [comment]
If you merge this branch you will also want to merge 
- https://github.com/f-o-a-m/purescript-web3/pull/154
- https://github.com/f-o-a-m/purescript-web3-generator/pull/67 (after changing ps-web3 ref)

Then you will need to update [chanterelle](https://github.com/f-o-a-m/chanterelle), and then go back through and update the [relevant test subdirectory](https://github.com/f-o-a-m/purescript-web3/tree/master/test/web3/Web3Spec/Live)

This is all tedious, but because there is currently no way (that I know of) to monorepo these projects in way that makes sense, all of things are usually done atomically.

**Comment by srghma** [comment]
hi

> merge

I don't have access to merge

> web3

hell, I just did what you did already. Will be checking prs from now on better

P.S. did it like this

```
-- | Read any number of HexDigits
take :: forall m. Monad m => Int -> ParserT HexString m HexString
take = \n -> unsafePartial fromJust <<< mkHexString <<< fromCharArray <$> replicateA n anyCharFromHexString
  where
    -- | it's safe to change "remaining input" type here
    -- | b.c. it's an input - it's already validated
    anyCharFromHexString :: ParserT HexString m Char
    anyCharFromHexString = (unsafeCoerce :: ParserT String m Char -> ParserT HexString m Char) anyChar
```

> chanterelle

ok

> update tests

ok, yes, they are failing rn

**Comment by srghma** [comment]
@martyall what do you think if we will make it `List String`?

**Comment by martyall** [comment]
I think it's fine to keep it at `String`, that way we keep all of the functions on `String` which are useful.

**Comment by martyall** [comment]
Closing in favor of #28

**Pull request closed without merging**
